name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v3
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: tss-sdk-go.exe
