name: Tests

on:
  workflow_dispatch:
  push:
    # Publish the `master` branch.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  pull_request:
    branches:
      - main

env:
  TSS_TENANT: ${{ secrets.TSS_TENANT }}
  TSS_USERNAME: ${{ secrets.TSS_USERNAME }}
  TSS_PASSWORD: ${{ secrets.TSS_PASSWORD }}
  TSS_SECRET_ID: ${{ secrets.TSS_SECRET_ID }}
  TSS_SECRET_PATH: ${{ secrets.TSS_SECRET_PATH }}
  TSS_TEMPLATE_ID: ${{ secrets.TSS_TEMPLATE_ID }}
  TSS_FOLDER_ID: ${{ secrets.TSS_FOLDER_ID }}
  TSS_SITE_ID: ${{ secrets.TSS_SITE_ID }}
  TSS_SSH_KEY_TEMPLATE_ID: ${{ secrets.TSS_SSH_KEY_TEMPLATE_ID }}
  TSS_TEST_PASSWORD: ${{ secrets.TSS_TEST_PASSWORD }}
  TSS_SEARCH_FIELD: ${{ secrets.TSS_SEARCH_FIELD }}
  TSS_SEARCH_TEXT: ${{ secrets.TSS_SEARCH_TEXT }}
  TSS_PLATFORM_USERNAME: ${{ secrets.TSS_PLATFORM_USERNAME }}
  TSS_PLATFORM_PASSWORD: ${{ secrets.TSS_PLATFORM_PASSWORD }}
  TSS_PLATFORM_URL: ${{ secrets.TSS_PLATFORM_URL }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./server

      - name: Test
        run: go test -v ./server