name: Tests

on:
  workflow_dispatch:
  push:
    # Publish the `master` branch.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
      
  pull_request:
    branches:
      - main

env:
  TSS_TENANT: ${{ secrets.TSS_TENANT }}
  TSS_USERNAME: ${{ secrets.TSS_USERNAME }}
  TSS_PASSWORD: ${{ secrets.TSS_PASSWORD }}
  TSS_SECRET_ID: ${{ secrets.TSS_SECRET_ID }}
  TSS_TEMPLATE_ID: ${{ secrets.TSS_TEMPLATE_ID }}
  TSS_FOLDER_ID: ${{ secrets.TSS_FOLDER_ID }}
  TSS_SITE_ID: ${{ secrets.TSS_SITE_ID }}
  TSS_SSH_KEY_TEMPLATE_ID: ${{ secrets.TSS_SSH_KEY_TEMPLATE_ID }}
  TSS_TEST_PASSWORD: ${{ secrets.TSS_TEST_PASSWORD }}
  TSS_SEARCH_FIELD: ${{ secrets.TSS_SEARCH_FIELD }}
  TSS_SEARCH_TEXT: ${{ secrets.TSS_SEARCH_TEXT }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...
